DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'poly-pooling'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : PoolPolyp                                           # name of the model you are using
  BACKBONE      : PoolFormer                                                      # model variant
  PRETRAINED    : 'checkpoints/poolformer_s36.pth' 

TRAIN:
  IMAGE_SIZE    : [352, 352]    # training image size in (h, w)
  BATCH_SIZE    : 8               # batch size used to train
  EPOCHS        : 20             # number of epochs to train
  EVAL_INTERVAL : 10              # evaluation interval during training

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0001          # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.6             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'poly-pooling/best.pth'     # trained model file path
  IMAGE_SIZE    : [352, 352]                            # evaluation image size in (h, w)                       